var levels = {
    1: {
        tileMap: 'level_1',
        tileSet: 'default_tileset',
        startX: 20,
        startY: 590,
        pirates: [

            {
                x: 920,
                y: 450,
                minX: 900,
                maxX: 970,
                speed: 75,
                key: 'pirate_1',
                weapon: false,
                weaponVelocity: false,
                attackInterval: false,
                startFrame: 4,
                direction: 'right',
            },

            {
                x: 700,
                y: 600,
                minX: 670,
                maxX: 800,
                speed: 75,
                key: 'pirate_1',
                weapon: false,
                weaponVelocity: false,
                attackInterval: false,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 1386,
                y: 515,
                minX: 1323,
                maxX: 1433,
                speed: 75,
                key: 'pirate_2',
                weapon: 'pirate_sword',
                weaponVelocity: 200,
                attackInterval: 2000,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 1610,
                y: 390,
                minX: 1540,
                maxX: 1660,
                speed: 75,
                key: 'pirate_1',
                weapon: false,
                weaponVelocity: false,
                attackInterval: false,
                startFrame: 8,
                direction: 'right',
            },
        ]
    },
    2: {
        tileMap: 'level_2',
        tileSet: 'default_tileset',
        startX: 20,
        startY: 0,
        pirates: [

            {
                x: 568,
                y: 230,
                minX: 452,
                maxX: 660,
                speed: 80,
                key: 'pirate_2',
                weapon: 'pirate_sword',
                weaponVelocity: 200,
                attackInterval: 1000,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 920,
                y: 450,
                minX: 900,
                maxX: 970,
                speed: 75,
                key: 'pirate_1',
                weapon: false,
                weaponVelocity: false,
                attackInterval: false,
                startFrame: 4,
                direction: 'right',
            },

            {
                x: 265,
                y: 136,
                minX: 223,
                maxX: 316,
                speed: 75,
                key: 'pirate_1',
                weapon: false,
                weaponVelocity: false,
                attackInterval: false,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 1386,
                y: 515,
                minX: 1323,
                maxX: 1433,
                speed: 75,
                key: 'pirate_2',
                weapon: 'pirate_sword',
                weaponVelocity: 200,
                attackInterval: 2000,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 1610,
                y: 390,
                minX: 1650,
                maxX: 1800,
                speed: 75,
                key: 'pirate_1',
                weapon: false,
                weaponVelocity: false,
                attackInterval: false,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 2850,
                y: 0,
                minX: 2850,
                maxX: 2900,
                speed: 75,
                key: 'pirate_2',
                weapon: 'pirate_sword',
                weaponVelocity: 200,
                attackInterval: 500,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 2800,
                y: 390,
                minX: 2810,
                maxX: 2850,
                speed: 75,
                key: 'pirate_2',
                weapon: 'pirate_sword',
                weaponVelocity: 200,
                attackInterval: 2000,
                startFrame: 8,
                direction: 'right',
            },

            {
                x: 3025,
                y: 390,
                minX: 3010,
                maxX: 3050,
                speed: 75,
                key: 'pirate_2',
                weapon: 'pirate_sword',
                weaponVelocity: 200,
                attackInterval: 2000,
                startFrame: 8,
                direction: 'right',
            },
        ],
        platforms: [
            {
                x: 1875,
                y: 740,
                minX: 1875,
                maxX: 2200,
                speed: 75,
                key: 'platform',
                direction: 'right',
            },

        ]
    }
}